import { useState } from "react";
import { Download, Eye, Save, ChevronDown } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import type { Template } from "@shared/schema";

interface TemplatePreviewProps {
  template: Template;
  extractedData: Record<string, any>;
  onSave?: () => void;
  onExport?: (format: 'pdf' | 'docx') => void;
  isSaving?: boolean;
}

export default function TemplatePreview({ 
  template, 
  extractedData, 
  onSave,
  onExport,
  isSaving = false
}: TemplatePreviewProps) {
  const [showFullPreview, setShowFullPreview] = useState(false);

  const renderTemplateContent = () => {
    // Generate dynamic document title based on template type
    const getDocumentTitle = () => {
      switch (template.type) {
        case 'TDS':
          return 'TECHNICAL DATA SHEET';
        case 'MDMS':
          return 'MATERIAL DATA MANAGEMENT SHEET';
        case 'CoA':
        default:
          return 'CERTIFICATE OF ANALYSIS';
      }
    };

    // Generate completely dynamic template structure
    return (
      <div className="space-y-6">
        {/* Dynamic Header */}
        <div className="text-center border-b border-gray-200 pb-4">
          <h1 className="text-xl font-bold text-gray-900 uppercase">
            {getDocumentTitle()}
          </h1>
        </div>

        {/* Dynamic Field Rendering */}
        <div className="space-y-3">
          {template.placeholders.map((placeholder: string) => {
            // Skip placeholders that don't have values and aren't in extracted data
            if (!extractedData[placeholder] && extractedData[placeholder] !== '') {
              return null;
            }

            const label = placeholder
              .replace(/_/g, ' ')
              .replace(/\b\w/g, (l: string) => l.toUpperCase());

            return (
              <div key={placeholder} className="flex justify-between items-center">
                <span className="font-medium text-gray-700">{label}:</span>
                <span className="text-primary-600 font-medium" data-testid={`preview-${placeholder}`}>
                  {extractedData[placeholder] || `{${placeholder}}`}
                </span>
              </div>
            );
          })}
        </div>

        {/* Dynamic Company Footer */}
        <div className="text-center border-t border-gray-200 pt-4">
          <p className="font-medium text-gray-900">Document Generated by ChemDoc AI</p>
        </div>
      </div>
    );
  };

  if (showFullPreview) {
    return (
      <Card className="p-6 max-w-4xl mx-auto">
        <div className="flex items-center justify-between mb-6">
          <h3 className="text-lg font-semibold text-gray-900">Full Document Preview</h3>
          <Button 
            variant="outline" 
            onClick={() => setShowFullPreview(false)}
            data-testid="button-close-preview"
          >
            Close Preview
          </Button>
        </div>
        
        <div className="bg-white border border-gray-200 rounded-lg p-8 mb-6 shadow-sm">
          {renderTemplateContent()}
        </div>

        <div className="flex space-x-2 justify-center">
          <Button 
            onClick={onSave}
            disabled={isSaving}
            data-testid="button-save-document"
          >
            <Save className="w-4 h-4 mr-2" />
            {isSaving ? 'Saving...' : 'Save Document'}
          </Button>
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="outline" data-testid="button-export-dropdown">
                <Download className="w-4 h-4 mr-2" />
                Export
                <ChevronDown className="w-4 h-4 ml-2" />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent>
              <DropdownMenuItem onClick={() => onExport?.('pdf')} data-testid="menu-export-pdf">
                <Download className="w-4 h-4 mr-2" />
                Export as PDF
              </DropdownMenuItem>
              <DropdownMenuItem onClick={() => onExport?.('docx')} data-testid="menu-export-docx">
                <Download className="w-4 h-4 mr-2" />
                Export as Word
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>
      </Card>
    );
  }

  return (
    <div>
      <h4 className="text-sm font-semibold text-gray-900 mb-4">Template Preview</h4>
      <div className="bg-gray-50 border border-gray-200 rounded-lg p-4 min-h-96">
        {renderTemplateContent()}
      </div>

      <div className="mt-4 flex space-x-2">
        <Button
          onClick={onSave}
          disabled={isSaving}
          data-testid="button-save-document"
        >
          <Save className="w-4 h-4 mr-2" />
          {isSaving ? 'Saving...' : 'Save Document'}
        </Button>
        
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant="outline" data-testid="button-export-dropdown">
              <Download className="w-4 h-4 mr-2" />
              Export
              <ChevronDown className="w-4 h-4 ml-2" />
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent>
            <DropdownMenuItem onClick={() => onExport?.('pdf')} data-testid="menu-export-pdf">
              <Download className="w-4 h-4 mr-2" />
              Export as PDF
            </DropdownMenuItem>
            <DropdownMenuItem onClick={() => onExport?.('docx')} data-testid="menu-export-docx">
              <Download className="w-4 h-4 mr-2" />
              Export as Word
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
        
        <Button 
          variant="outline" 
          onClick={() => setShowFullPreview(true)}
          data-testid="button-full-preview"
        >
          <Eye className="w-4 h-4 mr-2" />
          Full Preview
        </Button>
      </div>
    </div>
  );
}